### ISSUE TITLE
window.viewportUnitsBuggyfill.init   undefined

### ISSUE THREAD

**Issue by onyz4x** [PowerDos/Vue-Moblie-Templet-For-Vux#1]
clone 项目后运行  出现如下error
![image](https://user-images.githubusercontent.com/15812120/43944707-7071df1e-9cb2-11e8-83d0-9922e6a2aa27.png)

应该是"postcss-viewport-units": "^0.1.4"组件的问题

**Comment by PowerDos** [comment]
欢迎PR呀
